spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fdc?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create

fdc:
  file-storage:
    type: local
    local-temp-path: ${USERPROFILE}/.fdc/temp